-allowaccessmodification
-repackageclasses

# AndroidLibXrayLite is generated by gomobile and is called from native code.
# Keep these bindings exact while allowing the rest of the app to shrink aggressively.
-keep class go.** { *; }
-keep class libv2ray.** { *; }
